### ISSUE TITLE
screen allowed to timeout while the camera is on

### ISSUE THREAD

**Issue by steve47457** [GrapheneOS/Camera#105]
the device's screen is allowed to dim and turn off (screen timeout) while the camera is on, this should not happen on a camera app. thank you

Samsung Galaxy A03s

**Comment by thestinger** [comment]
There's a full wake lock while recording video. For when the camera preview is enabled, we can add a full wake lock keeping the screen on for a certain amount of time like 5 minutes. I don't think it makes sense to keep the screen / device on indefinitely just because the camera is open with the preview shown.

**Comment by empratyush** [comment]
done #154
