### ISSUE TITLE
[REQ] Advanced on-screen controls

### ISSUE THREAD

**Issue by forart** [GrapheneOS/Camera#232]
Hi there, this app is really interesting.

We do *strongly* suggest you to "grab" (or, even better, collaborate with) [Open Camera](https://opencamera.org.uk/) controls that are extremely useful for "advanced" shootings

For example:
- artificial horizon
- customizable EXIF photo tags (author, license)
- optional stamps on photos
- etc.

Hope that inspires !

**Comment by Zanthed** [comment]
In the future please split up your suggestions into separate issues. We can't track everything under one issue.

We can't use ANYTHING from Open Camera because they use a non-free/restrictive licence and we don't want to include GPLv3 or any variant of GPLv3 code into our project. Open Camera is not an objectively good camera and does not make use of the hardware fully. It's poor quality compared to our app. It's also fairly legacy and dinosaur and doesn't use CameraX.

> artificial horizon

We have a gyroscope suggestions toggle in More Settings.

> customizable EXIF photo tags (author, license)

These should be added yourself with a proper gallery app.
