### ISSUE TITLE
Swipe gesture in landscape mode

### ISSUE THREAD

**Issue by dhishkyaon** [GrapheneOS/Camera#248]
In Google Camera -

https://user-images.githubusercontent.com/88529066/171336137-83a1d787-2598-4d1f-8b9e-9b086e912a20.mp4

In GrapheneOS Camera -

https://user-images.githubusercontent.com/88529066/171336193-181209da-8fd0-4e4a-8213-f7f5436c89c5.mp4

**Comment by thestinger** [comment]
You need to describe what you want to see.

**Comment by dhishkyaon** [comment]
swipe gesture from Left to Right or Right to Left like Google's Camera app

**Comment by MHShetty** [comment]
Hi @dhishkyaon,

This issue has now been fixed in the latest changes pushed the repository. The app/fix can be tested either by cloning the repo/pulling the latest changes and then building the app. Please do let us know if any further changes are required by any chance.

Thanks a lot for carefully testing the app and reporting this issue @dhishkyaon!
