### ISSUE TITLE
16:9 Display Can't Adjust In Camera And Video Mde

### ISSUE THREAD

**Issue by IzumiSena** [GrapheneOS/Camera#52]
![Screenshot_20211105-154132_Camera](https://user-images.githubusercontent.com/61591769/140491021-c301e860-5ec8-44d7-8608-37ee197d471b.png)
![Screenshot_20211105-154202_Camera](https://user-images.githubusercontent.com/61591769/140491046-6e9364b8-cb0a-4d6a-b100-4e2352b3ba77.png)
![Screenshot_20211105-154214_Camera](https://user-images.githubusercontent.com/61591769/140491066-c2179c31-089b-4261-81f6-0a2b1822c588.png)

Its Happening Only if i use 16:9!
Works Fine in 4:3!

![Screenshot_20211105-154952_Gallery](https://user-images.githubusercontent.com/61591769/140491872-d13514e7-c398-4329-96c5-6c2fa973bab3.png)

![Screenshot_20211105-155006_Gallery](https://user-images.githubusercontent.com/61591769/140491967-fe03df19-f4bc-46da-beda-0a5c25412602.png)

4K video recording shows so much glitch! ... And if i try to see 4k recorded videos it's laggy!.
Version running (2)
Device Running (OG Pixel XL)
Don't Know if it will get fixed! For OG pixel!... At least showing this issue to you guys!
(Sorry for my bad English).

**Comment by MHShetty** [comment]
We only support devices that are officially supported by GrapheneOS.
https://grapheneos.org/faq#device-support

This issue seems to be on the end of the CameraX library as we aren't really controlling the low level stuff while recording a video. We have reported this issue to them and this should automatically get resolved once they fix it from their end and make a release that includes those changes and we upgrade to the latest/that version of the library.

The status of the issue can be tracked from here:  https://groups.google.com/a/android.com/g/camerax-developers/c/P6DORRXqspk

Thanks for reporting this issue!

**Comment by MHShetty** [comment]
You can track the status of this issue from here: https://issuetracker.google.com/issues/205340278

Once fixed, the issue should get resolved in the next release of the library. 

This might take a while as there hasn't been a release of the main library since a really long time.

**Comment by MHShetty** [comment]
@IzumiSena The issue with those colored lines have now been fixed by the CameraX team: https://issuetracker.google.com/issues/205340278

Hope they include the changes in the next release soon!

Thanks for filing this issue @IzumiSena!

**Comment by MHShetty** [comment]
The colored lines issue has now been fixed by the CameraX team and the width should fit better in the next release.

Thanks a lot for reporting these issues!
